FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE ${API_PORT}

CMD ["sh", "-c", "npx prisma migrate deploy && npx nodemon src/index.js"]
